app:
  image: tutum/hello-world:latest
  environment:
    SERVICE_80_NAME: http
    SERVICE_NAME: app
    SERVICE_TAGS: production
  ports:
  - "80"

lb:
  build: ./
  net: host
  ports:
  - "80:80"

consul:
  command: -bootstrap
  image: gliderlabs/consul-server
  net: host

registrator:
  command: consul://localhost:8500 -retry-attempts 10 -retry-interval 1000 -internal
  image: gliderlabs/registrator:latest
  net: host
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
